"""create complaint table

Revision ID: 75af667ff69d
Revises: cd4b15bf70e0
Create Date: 2022-10-26 12:57:25.385081

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "75af667ff69d"
down_revision = "cd4b15bf70e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum("VALID", "INVALID", "PENDING", name="status"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_complaints_id"), "complaints", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_complaints_id"), table_name="complaints")
    op.drop_table("complaints")
    # ### end Alembic commands ###
