name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 10s --health-timeout 5s --health-retries 10
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Cassandra init script
        run: |
          docker exec ${{ job.services.cassandra.id }} cqlsh localhost 9042 -e "CREATE KEYSPACE IF NOT EXISTS url_shortener WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : '1' };"
          docker exec ${{ job.services.cassandra.id }} cqlsh localhost 9042 -e "CREATE TABLE IF NOT EXISTS url_shortener.urls (key text PRIMARY KEY, reference text, owner_id int, action text, is_active boolean );"

      - name: Test with pytest
        run:  pytest --dburl $DATABASE_URL
